enable-module-update = true # set this to false if you do not want to receive updates for the module
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

# [YouTube]
# build-mode = "both"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
# uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

# [Music]
# build-mode = "both"
# arch = "both"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
# uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[YouTube-Morphe]
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
included-patches = "'Enable slide to seek' 'Custom branding'"
patcher-args = "-e 'Custom branding name for YouTube' -OappName='YouTub𝕖𝕏'"

# dont build on gh actions (https://github.com/j-hc/revanced-magisk-module/issues/554)
[Music-Morphe]
app-name = "Music"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "both"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[Reddit-Morphe]
app-name = "Reddit"
rv-brand = "Morphe"
build-mode = "both"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
dpi = "120-640dpi"

[TikTok-Morphe]
patches-source = "icysymmetra/tiktok-patches-for-morphe"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok/"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
# included-patches = "'SIM spoof'"

[Instagram-Morphe]
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram/"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"

[Pinterest-Morphe]
patches-source = "jkennethcarino/adobo"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/pinterest/pinterest-one-destination-for-a-world-of-inspiration/"
uptodown-dlurl = "https://pinterest.en.uptodown.com/android"

[Soundcloud-Morphe]
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/soundcloud/soundcloud-soundcloud/"
uptodown-dlurl = "https://soundcloud.en.uptodown.com/android"

[Camscanner-Morphe]
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/intsig-pte/camscanner-phone-pdf-creator/"
uptodown-dlurl = "https://camscanner-pdf-creator.en.uptodown.com/android"

[Macrofactor-Morphe]
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
arch = "both"
uptodown-dlurl = "https://macrofactor-diet-sidekick-and-macro-tracker.en.uptodown.com/android"

[GooglePhotos-Morphe]
patches-source = "RookieEnough/De-ReVanced"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "both"
arch = "both"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.photos"

[Disney-plus-Morphe]
patches-source = "RookieEnough/De-ReVanced"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/soundcloud/soundcloud-soundcloud/"
uptodown-dlurl = "https://soundcloud.en.uptodown.com/android"

[Duolingo-Morphe]
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/soundcloud/soundcloud-soundcloud/"
uptodown-dlurl = "https://soundcloud.en.uptodown.com/android"

[Messenger-Morphe]
patches-source = "RookieEnough/De-ReVanced"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android"

[Photomath-Morphe]
patches-source = "RookieEnough/De-ReVanced"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photomath/"
uptodown-dlurl = "https://photomath.en.uptodown.com/android"

[Pixiv-Morphe]
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/soundcloud/soundcloud-soundcloud/"
uptodown-dlurl = "https://soundcloud.en.uptodown.com/android"

[Prime-video-Morphe]
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-prime-video/"
uptodown-dlurl = "https://amazon-video.en.uptodown.com/android"

[Proton-mail-Morphe]
patches-source = "RookieEnough/De-ReVanced"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonmail-encrypted-email/"
uptodown-dlurl = "https://protonmail.en.uptodown.com/android"

[Proton-vpn-Morphe]
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonvpn-free-vpn-secure-unlimited-fdroid-version/"
uptodown-dlurl = "https://protonvpn.en.uptodown.com/android"

[Wallcraft-Morphe]
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/nebuchadnezzar-doo/wallpapers-hd-4k-backgrounds/"
uptodown-dlurl = "https://wallcraft.en.uptodown.com/android"

[Pandora-Morphe]
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/pandora/pandora-music-podcasts/"
uptodown-dlurl = "https://pandora.en.uptodown.com/android"

[Threads-Morphe]
patches-source = "RookieEnough/De-ReVanced"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/threads-an-instagram-app/"
uptodown-dlurl = "https://threads.en.uptodown.com/android"

[Crunchyroll-Morphe]
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/crunchyroll-llc-2/crunchyroll/"
uptodown-dlurl = "https://crunchyroll.en.uptodown.com/android"

[Tasker-Morphe]
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/joaomgcd/tasker/"

[Icon-pack-studio-Morphe]
patches-source = "RookieEnough/De-ReVanced"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/icon-pack-studio/"
uptodown-dlurl = "https://icon-pack-studio.en.uptodown.com/android"

[Windy-Morphe]
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/windy-weather-world-inc/windy-wind-weather-forecast/"
uptodown-dlurl = "https://windy.en.uptodown.com/android"

[FXfile-Morphe]
patches-source = "indrastorms/Dropped-Patches"
cli-source = "revanced/revanced-cli"
rv-brand = "Revanced"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/nextapp-inc/fx-file-explorer/"
uptodown-dlurl = "https://fx-file-explorer.en.uptodown.com/android"

[Smart_launcher-Morphe]
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/smart-launcher/"
uptodown-dlurl = "https://smart-launcher.en.uptodown.com/android"

[Podcast-Morphe]
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/xavier-guillemane/podcast-addict/"
uptodown-dlurl = "https://podcast-addict.en.uptodown.com/android"

[WPS-Office-Morphe]
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/wps-software-pte-ltd/wps-office-pdf/"
uptodown-dlurl = "https://wps-office.en.uptodown.com/android"

[Ibs_paint-Morphe]
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
arch = "both"
uptodown-dlurl = "https://ibispaint-x.en.uptodown.com/android"

[Gamehub-Morphe]
patches-source = "liaralabs/revanced-patches"
cli-source = "revanced/revanced-cli"
rv-brand = "Revanced"
arch = "both"
uptodown-dlurl = "https://com-xiaoji-egggame.en.uptodown.com/android"

[Windscribe-Morphe]
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/windscribe/windscribe-fast-secure-vpn-f-droid-version/"
uptodown-dlurl = "https://windscribe.en.uptodown.com/android"

[Spotify-Morphe]
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.spotify.music"
arch = "both"

[Twitter-Morphe]
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Piko"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"
build-mode = "module"
version = "11.81.0-release.0"
include-stock = "split"

[Facebook-Morphe]
patches-source = "RookieEnough/De-ReVanced"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook/"
uptodown-dlurl = "https://facebook.en.uptodown.com/android"

[Twitch-Morphe]
patches-source = "RookieEnough/De-ReVanced"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"
